services:
  - type: web
    name: lira-quotes
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
    healthCheckPath: /
